app/models.py
from app import db

class Location(db.Model):
    __table__ = db.metadata.tables["location"]
    
    def __str__(self):
        return self.name

class SexType(db.Model):
    __table__ = db.metadata.tables["sex_type"]
    
    def __str__(self):
        return self.name

class Student(db.Model):
    __table__ = db.metadata.tables["student"]
    
    tests = db.relationship(
        "Test", cascade="all,delete-orphan", lazy="selectin", back_populates="student"
    )
    
    sextype = db.relationship(
        "SexType", lazy=True
    )
    
    location = db.relationship(
        "Location", lazy=True
    )

class TestStatus(db.Model):
    __table__ = db.metadata.tables["test_status"]
    
    def __str__(self):
        return self.name
    
class Subject(db.Model):
    __table__ = db.metadata.tables["subject"]
    
    def __str__(self):
        return self.name

class Test(db.Model):
    __table__ = db.metadata.tables["test"]
    
    student = db.relationship(
        "Student", single_parent=True, back_populates="tests"
    )
    
    subject = db.relationship(
        "Subject", lazy=True
    )
    
    status = db.relationship(
        "TestStatus", lazy=True
    )
    
    location = db.relationship(
        "Location", lazy=True
    )

app/app.py
import os
import redis
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_mongoengine import MongoEngine

USER = os.environ["USER"]
PASSWORD = os.environ["PASSWORD"]
HOST = os.environ["HOST"]
PORT = os.environ["PORT"]
DB = os.environ["DB"]

REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]

ACTIVE_DB = os.environ["ACTIVE_DB"]

db = SQLAlchemy()
db_mongo = MongoEngine()
r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT)

def create_app():
    app = Flask(__name__)
    app.config.from_mapping({
        "SQLALCHEMY_DATABASE_URI": f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}/{DB}",
    })
    
    app.config["MONGODB_SETTINGS"] = [{
        "db": "zno",
        "host": "mongo",
        "port": 27017
    }]
    
    @app.cli.command("migrate-mongo")
    def migrate_mongo():
        from scripts.postgres_to_mongo import migrate
        migrate()        
 
    db.init_app(app)
    with app.app_context():
        db.reflect()
        
    db_mongo.init_app(app)

    import views
    app.register_blueprint(views.student_bp)
    app.register_blueprint(views.test_bp)
    app.register_blueprint(views.query_bp)
    
    @app.route("/", methods=["GET", "POST"])
    def root():
        return redirect(url_for("student.student_all"))

    return app

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for
import services

student_bp = Blueprint("student", __name__, url_prefix="/student")

@student_bp.route("/<uuid>", methods=["GET", "POST"])
def student(uuid):
    if request.method == "POST":
        services.delete_student(uuid)
        return redirect(url_for("student.student_all"))
    student = services.serialize_student(uuid)
    pcolumns = services.serialize_student_columns()
    tests = services.serialize_test_all(uuid)
    tcolumns = services.serialize_test_columns()
    return render_template(
        "student/student.html", 
        pcolumns=pcolumns,
        student=student,
        tcolumns=tcolumns,
        tests=tests
    )
    
@student_bp.route("/<uuid>/edit", methods=["GET", "POST"])
def student_edit(uuid):
    if request.method == "POST":
        services.update_student(uuid, request.form)
        return redirect(url_for("student.student", uuid=uuid))
    columns = services.serialize_student_columns()
    student = services.serialize_student(uuid)
    options = services.serialize_student_options()
    return render_template(
        "student/student_edit.html",
        columns=columns,
        student=student,
        options=options,
    )
    
@student_bp.route("/", methods=["GET"])
def student_all():
    students = services.serialize_student_all()
    columns = services.serialize_student_columns()
    return render_template(
        "student/student_all.html", 
        students=students,
        columns=columns
    )

@student_bp.route("/add", methods=["GET", "POST"])
def student_add():
    if request.method == "POST":
        services.create_student(request.form)
        return redirect(url_for("student.student_all"))
    columns = services.serialize_student_columns(exclude=["outid"])
    options = services.serialize_student_options()
    return render_template(
        "student/student_add.html",
        columns=columns,
        options=options,
    )

    
test_bp = Blueprint("test", __name__, url_prefix="/test")
@test_bp.route("/<student_uuid>/<id>", methods=["GET", "POST"])
def test(student_uuid, id):
    if request.method == "POST":
        services.delete_test(id)
        return redirect(url_for("student.student", uuid=student_uuid))
    test = services.serialize_test(id)
    columns = services.serialize_test_columns()
    return render_template(
        "test/test.html", 
        columns=columns,
        test=test
    )

@test_bp.route("/add/<student_uuid>", methods=["GET", "POST"])
def test_add(student_uuid):
    if request.method == "POST":
        services.create_test(student_uuid, request.form)
        return redirect(url_for("student.student", uuid=student_uuid))
    columns = services.serialize_test_columns(exclude=["id"])
    student = services.serialize_student(student_uuid)
    options = services.serialize_test_options()
    return render_template(
        "test/test_add.html",
        columns=columns,
        student=student,
        options=options,
    )

@test_bp.route("/edit/<student_uuid>/<id>", methods=["GET", "POST"])
def test_edit(student_uuid, id):
    if request.method == "POST":
        services.update_test(id, request.form)
        return redirect(url_for("student.student", uuid=student_uuid))
    columns = services.serialize_test_columns()
    test = services.serialize_test(id)
    options = services.serialize_test_options()
    return render_template(
        "test/test_edit.html",
        columns=columns,
        test=test,
        options=options,
    )

query_bp = Blueprint("query", __name__, url_prefix="/query")
@query_bp.route("/", methods=["GET", "POST"])
def query():
    if request.method == "POST":
        query_result = services.query(request.form)
        return  render_template(
            "query/query_result.html",
            query_result=query_result   
        )
    options = services.serialize_test_options()
    return render_template(
        "query/query.html",
        options=options
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="nav" style="margin: 12px">
        <a class="nav-link" href="{{ url_for('student.student_all') }}">ZNO Results [2019-2020]</a>
        <a class="nav-link" href="{{ url_for('query.query') }}">Query</a>
    </nav>

    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
    </script>
</body>

</html>

app/templates/query/query.html
{% extends 'base.html' %}

{% block title %} Query {% endblock %}

{% block content %}
<form method="post">
    <div class="form-group">
        <label for="year">Year</label>
        <input class="form-control" id="year" name="year">
    </div>
    <div class="form-group">
        <label for="location">Location</label>
        <select id="location" name="location_id" class="form-select">
            <option value="">All</option>
            {% for option in options.location %}
            <option value="{{ option.id }}">{{ option }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="subject">Subject</label>
        <select id="subject" name="subject_id" class="form-select">
            <option value="">All</option>
            {% for option in options.subject %}
            <option value="{{ option.id }}">{{ option }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Query</button>
    </div>
</form>
{% endblock %}

app/templates/query/query_result.html
{% extends 'base.html' %}

{% block title %} Query result {% endblock %}
{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Year</th>
            <th>Location</th>
            <th>AVG(ball100)</th>
        </tr>
    </thead>
    <tbody>
        {% for row in query_result %}
        <tr>
            <td>
                {{ row.year }}
            </td>
            <td>
                {{ row.location }}
            </td>
            <td>
                {{ row.bavg }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/student/student.html
{% extends 'base.html' %}

{% block title %} Student {% endblock %}

{% block content %}
<!-- Upper Section -->
<div class="row mt-3">
    <div class="col-md-6">
        {% for column in pcolumns %}
        <div class="form-group">
            <label for={{column}}>{{column}}</label>
            <p class="form-control" id="{{ column }}" name="{{ column }}">{{ student[column] }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-6">
        <form class="btn-group" method="post">
            <a type="button" class="btn btn-primary" href="{{ url_for('student.student_edit', uuid=student['outid']) }}">Edit</a>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>
<!-- Lower Section -->
<a type="button" class="btn btn-primary" href="{{ url_for('test.test_add', student_uuid=student['outid']) }}">Add test</a>
<div class="row mt-3">
    <div class="col">
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for column in tcolumns %}
                    <th>{{ column }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for test in tests %}
                <tr>
                    {% for column in tcolumns %}
                    <td>
                        <a href="{{ url_for('test.test', id=test['id'], student_uuid=test['outid']) }}">
                        {{ test[column] }}
                        </a>
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/student/student_add.html
{% extends 'base.html' %}

{% block title %} Student Add {% endblock %}

{% block content %}
<!-- Upper Section -->
<form method="post">
    {% for column in columns %}
    <div class="form-group">
        <label for="{{ column }}">{{ column }}</label>
        {% if column in ("sextype", "location") %}
        <select id="{{ column }}" name="{{ column }}_id" class="form-select">
            {% for option in options[column] %}
            <option value="{{ option.id }}">{{ option }}</option>
            {% endfor %}
        </select>
        {% else %}
        <input class="form-control" id="{{ column }}" name="{{ column }}">
        {% endif %}
    </div>
    {% endfor %}
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Add</button>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Back</button>
    </div>
</form>
{% endblock %}

app/templates/student/student_all.html
{% extends 'base.html' %}

{% block title %} Students {% endblock %}

{% block content %}
<a type="button" class="btn btn-primary" href="{{ url_for('student.student_add') }}">Add student</a>
<table class="table">
    <thead>
        <tr>
            {% for column in columns %}
                <th scope="col">{{column}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                {% for column in columns %}
                    <td>
                      <a href="{{ url_for('student.student', uuid=student['outid']) }}">
                        {{ student[column] }}
                      </a>
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/student/student_edit.html
{% extends 'base.html' %}

{% block title %} Student Edit {% endblock %}

{% block content %}
<!-- Upper Section -->
<form method="post">
    {% for column in columns %}
    <div class="form-group">
        <label for="{{ column }}">{{ column }}</label>
        {% if column in ("sextype", "location") %}
        <select id="{{ column }}" name="{{ column }}_id" class="form-select">
            {% for option in options[column] %}
            <option value="{{ option.id }}" {{ 'selected' if student[column].id == option.id }}>{{ option }}</option>
            {% endfor %}
        </select>
        {% elif column == "outid" %}
        <p id="{{ column }}" name="{{ column }}">{{ student[column] }}</p>
        {% else %}
        <input class="form-control" id="{{ column }}" name="{{ column }}" placeholder="{{ student[column] }}">
        {% endif %}
    </div>
    {% endfor %}
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Update</button>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Back</button>
    </div>
</form>
{% endblock %}